### ISSUE TITLE
Question: Why did you decide to use Salt over Ansible?

### ISSUE THREAD

**Issue by jack17529** [mazzy89/saltstack-helm#1]
Why did you decide to use Salt over Ansible or any other configuration management tool for that matter?

Hi Salvatore, do you remember me?

**Comment by mazzy89** [comment]
Not sure which matter you are talking about. The repository exists because no saltstack master helm existed before upstream. Closing ecause there is no much else to discuss and the question is not related to the content of the repo itself and not an issue about helm.
